In [3]:
import numpy as np


arr = np.random.randint(1, 101, size=(5, 5))
print("Original Array:\n", arr)


middle_element = arr[2, 2]
print("Middle Element:", middle_element)


row_means = np.mean(arr, axis=1)
print("Mean of each row:", row_means)


overall_mean = np.mean(arr)
greater_than_mean = arr[arr > overall_mean]
print("Elements greater than overall mean:", greater_than_mean)


def numpy_spiral_order(matrix):
    result = []
    while matrix.size:
        result.extend(matrix[0])
        matrix = np.rot90(matrix[1:])
    return result


spiral_order = numpy_spiral_order(arr)
print("Spiral Order of the array:", spiral_order)


Original Array:
 [[88 80 78 94 22]
 [ 7 16 86 81 33]
 [75 81 19 72 70]
 [94 76 28 54 59]
 [95 59 27 46 75]]
Middle Element: 19
Mean of each row: [72.4 44.6 63.4 62.2 60.4]
Elements greater than overall mean: [88 80 78 94 86 81 75 81 72 70 94 76 95 75]
Spiral Order of the array: [88, 80, 78, 94, 22, 33, 70, 59, 75, 46, 27, 59, 95, 94, 75, 7, 16, 86, 81, 72, 54, 28, 76, 81, 19]
